package com.google.android.gms.measurement.internal;

import com.baidu.idl.face.platform.FaceEnvironment;
import com.google.common.annotations.VisibleForTesting;
import com.google.firebase.perf.util.Constants;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashSet;
import java.util.List;
import org.apache.commons.lang3.time.DateUtils;

public final class zzfx {
    public static final zzfw zzA = zza("measurement.sgtm.upload.batches_retrieval_limit", 5, 5, zzcl.zza, false);
    public static final zzfw zzB = zza("measurement.sgtm.upload.min_delay_after_startup", 5000L, 5000L, zzcm.zza, false);
    public static final zzfw zzC = zza("measurement.sgtm.upload.min_delay_after_broadcast", 1000L, 1000L, zzcn.zza, false);
    public static final zzfw zzD = zza("measurement.sgtm.upload.min_delay_after_background", 600000L, 600000L, zzco.zza, false);
    public static final zzfw zzE = zza("measurement.sgtm.batch.long_queuing_threshold", 14400000L, 14400000L, zzcp.zza, false);
    public static final zzfw zzF = zza("measurement.upload.backoff_period", 43200000L, 43200000L, zzcr.zza, false);
    public static final zzfw zzG;
    public static final zzfw zzH;
    public static final zzfw zzI = zza("measurement.upload.realtime_upload_interval", 10000L, 10000L, zzcu.zza, false);
    public static final zzfw zzJ = zza("measurement.upload.debug_upload_interval", 1000L, 1000L, zzcv.zza, false);
    public static final zzfw zzK = zza("measurement.upload.minimum_delay", 500L, 500L, zzcw.zza, false);
    public static final zzfw zzL;
    public static final zzfw zzM;
    public static final zzfw zzN = zza("measurement.upload.refresh_blacklisted_config_interval", 604800000L, 604800000L, zzcz.zza, false);
    public static final zzfw zzO;
    public static final zzfw zzP = zza("measurement.upload.retry_time", 1800000L, 1800000L, zzdc.zza, false);
    public static final zzfw zzQ = zza("measurement.upload.retry_count", 6, 6, zzdd.zza, false);
    public static final zzfw zzR = zza("measurement.upload.max_queue_time", 518400000L, 518400000L, zzde.zza, false);
    public static final zzfw zzS = zza("measurement.upload.google_signal_max_queue_time", 300000L, 300000L, zzdf.zza, false);
    public static final zzfw zzT = zza("measurement.lifetimevalue.max_currency_tracked", 4, 4, zzdg.zza, false);
    public static final zzfw zzU = zza("measurement.audience.filter_result_max_count", 200, 200, zzdh.zza, false);
    public static final zzfw zzV = zza("measurement.upload.max_public_user_properties", 100, 100, (zzbn) null, false);
    public static final zzfw zzW;
    public static final zzfw zzX = zza("measurement.upload.max_public_event_params", 100, 100, (zzbn) null, false);
    public static final zzfw zzY = zza("measurement.service_client.idle_disconnect_millis", 5000L, 5000L, zzdi.zza, false);
    public static final zzfw zzZ = zza("measurement.service_client.reconnect_millis", 1000L, 1000L, zzdj.zza, false);
    public static final zzfw zza = zza("measurement.ad_id_cache_time", 10000L, 10000L, zzfq.zza, false);
    public static final zzfw zzaA;
    public static final zzfw zzaB = zza("measurement.rb.attribution.notify_app_delay_millis", 3000, 3000, zzeq.zza, false);
    public static final zzfw zzaC;
    public static final zzfw zzaD;
    public static final zzfw zzaE;
    public static final zzfw zzaF;
    public static final zzfw zzaG;
    public static final zzfw zzaH;
    public static final zzfw zzaI;
    public static final zzfw zzaJ = zza("measurement.service.storage_consent_support_version", 203600, 203600, zzey.zza, false);
    public static final zzfw zzaK;
    public static final zzfw zzaL;
    public static final zzfw zzaM;
    public static final zzfw zzaN;
    public static final zzfw zzaO;
    public static final zzfw zzaP;
    public static final zzfw zzaQ;
    public static final zzfw zzaR;
    public static final zzfw zzaS;
    public static final zzfw zzaT;
    public static final zzfw zzaU;
    public static final zzfw zzaV;
    public static final zzfw zzaW;
    public static final zzfw zzaX;
    public static final zzfw zzaY;
    public static final zzfw zzaZ;
    public static final zzfw zzaa;
    public static final zzfw zzab = zza("measurement.test.string_flag", "---", "---", zzdl.zza, false);
    public static final zzfw zzac = zza("measurement.test.long_flag", -1L, -1L, zzdn.zza, false);
    public static final zzfw zzad = zza("measurement.test.int_flag", -2, -2, zzdp.zza, false);
    public static final zzfw zzae;
    public static final zzfw zzaf = zza("measurement.experiment.max_ids", 50, 50, zzdr.zza, false);
    public static final zzfw zzag = zza("measurement.upload.max_item_scoped_custom_parameters", 27, 27, zzds.zza, false);
    public static final zzfw zzah = zza("measurement.upload.max_event_parameter_value_length", 500, 500, zzdt.zza, true);
    public static final zzfw zzai = zza("measurement.max_bundles_per_iteration", 100, 100, zzdu.zza, false);
    public static final zzfw zzaj = zza("measurement.sdk.attribution.cache.ttl", 604800000L, 604800000L, zzdv.zza, false);
    public static final zzfw zzak = zza("measurement.redaction.app_instance_id.ttl", 7200000L, 7200000L, zzdw.zza, false);
    public static final zzfw zzal = zza("measurement.rb.attribution.client.min_ad_services_version", 7, 7, zzdy.zza, false);
    public static final zzfw zzam = zza("measurement.dma_consent.max_daily_dcu_realtime_events", 1, 1, zzdz.zza, false);
    public static final zzfw zzan = zza("measurement.rb.attribution.uri_scheme", "https", "https", zzea.zza, false);
    public static final zzfw zzao = zza("measurement.rb.attribution.uri_authority", "google-analytics.com", "google-analytics.com", zzeb.zza, false);
    public static final zzfw zzap = zza("measurement.rb.attribution.uri_path", "privacy-sandbox/register-app-conversion", "privacy-sandbox/register-app-conversion", zzec.zza, false);
    public static final zzfw zzaq;
    public static final zzfw zzar = zza("measurement.rb.attribution.app_allowlist", "com.labpixies.flood", "com.labpixies.flood", zzee.zza, false);
    public static final zzfw zzas = zza("measurement.rb.attribution.user_properties", "_npa,npa|_fot,fot", "_npa,npa|_fot,fot", zzef.zza, false);
    public static final zzfw zzat = zza("measurement.rb.attribution.event_params", "value|currency", "value|currency", zzeg.zza, false);
    public static final zzfw zzau = zza("measurement.rb.attribution.query_parameters_to_remove", "", "", zzeh.zza, false);
    public static final zzfw zzav = zza("measurement.rb.attribution.max_queue_time", 864000000L, 864000000L, zzej.zza, false);
    public static final zzfw zzaw = zza("measurement.rb.attribution.max_retry_delay_seconds", 16, 16, zzek.zza, false);
    public static final zzfw zzax = zza("measurement.rb.attribution.client.min_time_after_boot_seconds", 90, 90, zzel.zza, false);
    public static final zzfw zzay = zza("measurement.rb.max_trigger_registrations_per_day", 1000, 1000, zzen.zza, false);
    public static final zzfw zzaz;
    public static final zzfw zzb;
    public static final zzfw zzba;
    public static final zzfw zzbb;
    public static final zzfw zzbc;
    public static final zzfw zzbd;
    public static final zzfw zzbe;
    public static final zzfw zzbf;
    public static final zzfw zzbg;
    public static final zzfw zzbh = zza("measurement.gbraid_compaign.compaign_params_triggering_info_update", "gclid,gbraid,gad_campaignid", "gclid,gbraid,gad_campaignid", zzbt.zza, false);
    public static final zzfw zzbi;
    public static final zzfw zzbj = zza("measurement.edpb.events_cached_in_no_data_mode", "_f,_v,_cmp", "_f,_v,_cmp", zzbu.zza, false);
    /* access modifiers changed from: private */
    public static final List zzbk = Collections.synchronizedList(new ArrayList());
    public static final zzfw zzc;
    public static final zzfw zzd;
    public static final zzfw zze = zza("measurement.config.url_scheme", "https", "https", zzdb.zza, false);
    public static final zzfw zzf = zza("measurement.config.url_authority", "app-measurement.com", "app-measurement.com", zzdm.zza, false);
    public static final zzfw zzg = zza("measurement.upload.max_bundles", 100, 100, zzdx.zza, false);
    public static final zzfw zzh = zza("measurement.upload.max_batch_size", 65536, 65536, zzei.zza, false);
    public static final zzfw zzi = zza("measurement.upload.max_bundle_size", 65536, 65536, zzet.zza, false);
    public static final zzfw zzj = zza("measurement.upload.max_events_per_bundle", 1000, 1000, zzfe.zza, false);
    public static final zzfw zzk = zza("measurement.upload.max_events_per_day", 100000, 100000, zzfp.zza, false);
    public static final zzfw zzl = zza("measurement.upload.max_error_events_per_day", 1000, 1000, zzbv.zza, false);
    public static final zzfw zzm = zza("measurement.upload.max_public_events_per_day", 50000, 50000, zzbw.zza, false);
    public static final zzfw zzn = zza("measurement.upload.max_conversions_per_day", 10000, 10000, zzbx.zza, false);
    public static final zzfw zzo = zza("measurement.upload.max_realtime_events_per_day", 10, 10, zzby.zza, false);
    public static final zzfw zzp = zza("measurement.store.max_stored_events_per_app", 100000, 100000, zzbz.zza, false);
    public static final zzfw zzq = zza("measurement.upload.url", "https://app-measurement.com/a", "https://app-measurement.com/a", zzca.zza, false);
    public static final zzfw zzr = zza("measurement.sgtm.google_signal.url", "https://app-measurement.com/s/d", "https://app-measurement.com/s/d", zzcb.zza, false);
    public static final zzfw zzs = zza("measurement.sgtm.service_upload_apps_list", "", "", zzcc.zza, false);
    public static final zzfw zzt = zza("measurement.sgtm.upload.backoff_http_codes", "404,429,503,504", "404,429,503,504", zzcd.zza, false);
    public static final zzfw zzu = zza("measurement.sgtm.upload.retry_interval", 600000L, 600000L, zzce.zza, false);
    public static final zzfw zzv = zza("measurement.sgtm.upload.retry_max_wait", 21600000L, 21600000L, zzcg.zza, false);
    public static final zzfw zzw = zza("measurement.sgtm.batch.retry_interval", 1800000L, 1800000L, zzch.zza, false);
    public static final zzfw zzx = zza("measurement.sgtm.batch.retry_max_wait", 21600000L, 21600000L, zzci.zza, false);
    public static final zzfw zzy = zza("measurement.sgtm.batch.retry_max_count", 10, 10, zzcj.zza, false);
    public static final zzfw zzz = zza("measurement.sgtm.upload.max_queued_batches", 5000, 5000, zzck.zza, false);

    static {
        Collections.synchronizedSet(new HashSet());
        Long valueOf = Long.valueOf(DateUtils.MILLIS_PER_HOUR);
        zzb = zza("measurement.app_uninstalled_additional_ad_id_cache_time", valueOf, valueOf, zzbo.zza, false);
        Long valueOf2 = Long.valueOf(DateUtils.MILLIS_PER_DAY);
        zzc = zza("measurement.monitoring.sample_period_millis", valueOf2, valueOf2, zzcf.zza, false);
        zzd = zza("measurement.config.cache_time", valueOf2, valueOf, zzcq.zza, false);
        zzG = zza("measurement.upload.window_interval", valueOf, valueOf, zzcs.zza, false);
        zzH = zza("measurement.upload.interval", valueOf, valueOf, zzct.zza, false);
        Long valueOf3 = Long.valueOf(DateUtils.MILLIS_PER_MINUTE);
        zzL = zza("measurement.alarm_manager.minimum_interval", valueOf3, valueOf3, zzcx.zza, false);
        zzM = zza("measurement.upload.stale_data_deletion_interval", valueOf2, valueOf2, zzcy.zza, false);
        Long valueOf4 = Long.valueOf(FaceEnvironment.TIME_DETECT_MODULE);
        zzO = zza("measurement.upload.initial_upload_delay_time", valueOf4, valueOf4, zzda.zza, false);
        Integer valueOf5 = Integer.valueOf(Constants.MAX_URL_LENGTH);
        zzW = zza("measurement.upload.max_event_name_cardinality", valueOf5, valueOf5, (zzbn) null, false);
        Boolean bool = Boolean.FALSE;
        zzaa = zza("measurement.test.boolean_flag", bool, bool, zzdk.zza, false);
        zza("measurement.test.cached_long_flag", -1L, -1L, zzdo.zza, true);
        Double valueOf6 = Double.valueOf(-3.0d);
        zzae = zza("measurement.test.double_flag", valueOf6, valueOf6, zzdq.zza, false);
        zzaq = zza("measurement.session.engagement_interval", valueOf, valueOf, zzed.zza, false);
        zza("measurement.rb.attribution.max_trigger_uris_queried_at_once", 0, 0, zzem.zza, false);
        Boolean bool2 = Boolean.TRUE;
        zzaz = zza("measurement.config.bundle_for_all_apps_on_backgrounded", bool2, bool2, zzeo.zza, false);
        zzaA = zza("measurement.config.notify_trigger_uris_on_backgrounded", bool2, bool2, zzep.zza, false);
        zzaC = zza("measurement.quality.checksum", bool, bool, (zzbn) null, false);
        zzaD = zza("measurement.audience.use_bundle_end_timestamp_for_non_sequence_property_filters", bool, bool, zzer.zza, false);
        zzaE = zza("measurement.audience.refresh_event_count_filters_timestamp", bool, bool, zzes.zza, false);
        zzaF = zza("measurement.audience.use_bundle_timestamp_for_event_count_filters", bool, bool, zzeu.zza, true);
        zzaG = zza("measurement.sdk.collection.last_deep_link_referrer_campaign2", bool, bool, zzev.zza, false);
        zzaH = zza("measurement.integration.disable_firebase_instance_id", bool, bool, zzew.zza, false);
        zzaI = zza("measurement.collection.service.update_with_analytics_fix", bool, bool, zzex.zza, false);
        zzaK = zza("measurement.service.store_null_safelist", bool2, bool2, zzez.zza, false);
        zzaL = zza("measurement.service.store_safelist", bool2, bool2, zzfa.zza, false);
        zzaM = zza("measurement.session_stitching_token_enabled", bool, bool, zzfb.zza, false);
        zzaN = zza("measurement.sgtm.client.upload_on_backgrounded.dev", bool, bool, zzfc.zza, true);
        zzaO = zza("measurement.gmscore_client_telemetry", bool, bool, zzft.zza, false);
        zzaP = zza("measurement.rb.attribution.service", bool2, bool2, zzfd.zza, true);
        zzaQ = zza("measurement.rb.attribution.client2", bool2, bool2, zzff.zza, true);
        zzaR = zza("measurement.rb.attribution.uuid_generation", bool2, bool2, zzfg.zza, false);
        zzaS = zza("measurement.rb.attribution.enable_trigger_redaction", bool2, bool2, zzfh.zza, false);
        zza("measurement.rb.attribution.followup1.service", bool, bool, zzfi.zza, false);
        zzaT = zza("measurement.rb.attribution.retry_disposition", bool, bool, zzfj.zza, false);
        zzaU = zza("measurement.client.sessions.enable_fix_background_engagement", bool, bool, zzfv.zza, false);
        zzaV = zza("measurement.set_default_event_parameters_propagate_clear.service.dev", bool2, bool2, zzfk.zza, false);
        zzaW = zza("measurement.set_default_event_parameters_propagate_clear.client.dev", bool2, bool2, zzfl.zza, false);
        zzaX = zza("measurement.service.ad_impression.convert_value_to_double", bool2, bool2, zzfm.zza, false);
        zza("measurement.rb.attribution.service.enable_max_trigger_uris_queried_at_once", bool2, bool2, zzfn.zza, false);
        zza("measurement.remove_conflicting_first_party_apis.dev", bool, bool, zzfo.zza, false);
        zzaY = zza("measurement.rb.attribution.service.trigger_uris_high_priority", bool2, bool2, zzbp.zza, false);
        zzaZ = zza("measurement.tcf.consent_fix", bool, bool, zzbq.zza, false);
        zzba = zza("measurement.tcf.empty_pref_fix", bool2, bool2, zzbr.zza, false);
        zzbb = zza("measurement.experiment.enable_phenotype_experiment_reporting", bool2, bool2, zzbs.zza, false);
        zzbc = zza("measurement.set_default_event_parameters.fix_service_request_ordering", bool, bool, zzbj.zza, false);
        zzbd = zza("measurement.set_default_event_parameters.fix_app_update_logging", bool2, bool2, zzbi.zza, false);
        zzbe = zza("measurement.service.fix_stop_bundling_bug", bool2, bool2, zzbm.zza, false);
        zzbf = zza("measurement.fix_params_logcat_spam", bool2, bool2, zzbl.zza, false);
        zzbg = zza("measurement.gbraid_campaign.stop_lgclid", bool, bool, zzfs.zza, false);
        zzbi = zza("measurement.edpb.service", bool, bool, zzbk.zza, false);
    }

    @VisibleForTesting
    public static zzfw zza(String str, Object obj, Object obj2, zzbn zzbn, boolean z) {
        zzfw zzfw = new zzfw(str, obj, obj2, zzbn, (byte[]) null);
        if (z) {
            zzbk.add(zzfw);
        }
        return zzfw;
    }
}
