package com.ktakilat.cbase.http.phone;

import java.util.List;

public class DeviceExInfo {
    public boolean allowMockLocation;
    public String appSign;
    public String basebandVersion;
    public String battery;
    public int batteryTemp;
    public String blackbox;
    public String blueMac;
    public String bluetooth;
    public String brand;
    public int brightness;
    public List<CalendarInfo> calendar;
    public String cameraNum;
    public String cpuHardware;
    public int dbm;
    public String diskFreeSpace;
    public String diskSpace;
    public String fingerPrint;
    public String freeMemory;
    public String gaid;
    public String imsi;
    public boolean isAcCharge;
    public boolean isCharging;
    public boolean isDebug;
    public String isNetworkingRoaming;
    public boolean isProxy;
    public boolean isRoot;
    public boolean isSimulator;
    public boolean isUsbCharge;
    public String kernelVersion;
    public int keyboard;
    public long lastBootTime;
    public String localDisplayLanguage;
    public String localIso3Country;
    public String localIso3Language;
    public String macAddress;
    public String manufacturer;
    public String modelNo;
    public String networkCountryIso;
    public String networkOperator;
    public String networkType;
    public String osVersion;
    public String screenHeight;
    public String screenWidth;
    public String sensor;
    public String serialNo;
    public String simCountryIso;
    public String simOperator;
    public String simOperatorName;
    public String timezone;
    public String totalMemory;
    public String upTime;
    public String wifiBSSID;
    public String wifiRSSI;
    public String wifiSSID;
}
